### PR TITLE
Make shops' addresses links to open Apple/Google Maps

### LINKED ISSUE #2: Make address work on mobile iOS & android
The address should be clickable and launch the respective Maps apps for directions

### PR DESCRIPTION
**Pull request by duncanleo**
This PR makes the shops' addresses links and sets a special `href` with their location coordinates.

See:
- http://tebros.com/2016/02/launching-external-maps-app-from-ionic2/
- https://stackoverflow.com/questions/10527983/best-way-to-detect-mac-os-x-or-windows-computers-with-javascript-or-jquery

Closes #2.

### CODE REVIEW

**Review by alphatrl — DISMISSED** [review]
Does nothing on Windows

**Comment by duncanleo** [comment]
@alphatrl https://docs.microsoft.com/en-us/previous-versions/windows/apps/jj635237(v=win.10)

**Comment by chesterhow** [comment]
Same it doesnt do anything on Windows

**Comment by alphatrl** [comment]
Check if it works on Windows and Android

**Comment by duncanleo** [comment]
@alphatrl the link launches Google Maps on Android but it takes a long time before displaying the coordinates in the search box. Also it doesn't trigger directions.

**Comment by duncanleo** [comment]
@alphatrl works on Android

**Review by chesterhow — APPROVED** [review]

**Pull request merged**
